name: my first workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout to repo
              uses: actions/checkout@v4
              
            - run: echo "welcome to learning of github actions"
              name: Welcome message

            - name: List files
              run: ls -ltrh
              
            - name: Read file
              run: cat README.md

           