name: my first workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout to repo
              uses: actions/checkout@v4

            - name: run multiple commands
              run: |
                echo "welcome to learning of github actions"
                ls -ltrh
                cat README.md
              
            - name: generate ASCII artwork
              run: cowsay -f dragon "Yeehaw! I summon a dragon!" >> dragon.txt

           